wip
* All unit tests pass
* All scripted tests but `run-services` pass. Issue is serialization of ServiceAcl

lagom-service-registry - Exception in RestCallId{method=PUT, pathPattern='/services/:id'}
com.lightbend.lagom.api.deser.DeserializationException: No suitable constructor found for type [simple type, class com.lightbend.lagom.internal.api.ServiceAcl]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)